### PR TITLE
crypto: fix a kernel panic on arm64 architecture in header encryption

### PR DESCRIPTION
**Pull request by pengtaohe**
When skcipher_request::src or skcipher_request::dst refers to a stack space, an 'Oops: Fatal exception' will be triggered.

### CODE REVIEW

**Comment by moritzbuhl** [comment]
Why not make it two u8[16] on stack?

**Comment by pengtaohe** [comment]
Hi, Xin Long:
Thanks for your good suggestions.
I have modified the code and commit subject as suggested. Please review it.

**Comment by lxin** [comment]
Applied, thanks.

**Comment by lxin** [comment]
@pengtaohe Just FYI:  after applying the patch, your name doesn't show up in the 'contributors' of this repo. I guess it's because the email on your git account is different from the one you used in this commit. You may go https://github.com/settings/emails and add the email in your patch to 'add Email address'.

**Comment by pengtaohe** [comment]
@lxin Yes, your guess is correct. This also prevents me from receiving messages in time. The email has been added now. Thanks.

**Pull request merged**
